### ISSUE TITLE
Radial bar differs between Chrome and Firefox

### ISSUE THREAD

**Issue by DamianGlowala** [wyzantinc/vue-radial-progress#28] opened 2020-02-02 11:49 UTC
There is an issue with displaying progress bar at step 0 on Firefox. It does not disappear completely, but on Chrome it behaves properly. Would be helpful when one wants to surround the icon with progress bar and hide it until the icon gets pressed.

**CHROME**
![image](https://user-images.githubusercontent.com/48835293/73607656-cd59da80-45b0-11ea-97ba-adfb5ab4d8e2.png)

**FIREFOX**
![image](https://user-images.githubusercontent.com/48835293/73607663-e5c9f500-45b0-11ea-85fc-e748afb07090.png)

**Comment by signalwerk** [comment] 2020-02-03 22:21
@DamianGlowala Hmm... When I go to https://wyzantinc.github.io/vue-radial-progress/ and reproduce your example I get under FireFox 72.0.2 (64-bit) the following output:

<img width="441" alt="Screenshot 2020-02-03 at 23 20 13" src="https://user-images.githubusercontent.com/992878/73696101-d4313c00-46db-11ea-93ab-09d50b0628f9.png">

How can I reproduce your example?

**Comment by mca312** [comment] 2020-02-13 22:13
@DamianGlowala I tested on FF v73 and cannot reproduce.  What version are you using?

**Comment by DamianGlowala** [comment] 2020-02-14 21:02
Getting back with the answer with a slight delay, as I wanted to find out what may be causing the issue. My FF version is 73 as well. It seems like the difference is related to my device, which is quite bizarre. I will share the solution if I manage to find it. Thanks for the support!

**Comment by mca312** [comment] 2020-02-14 21:11
Closing issue.  Reopen if you find the issue.  Thanks

**Closed by mca312** 2020-02-14 21:11 UTC
